version: "3.3"
services:
  rtsp-yolo-python:
    build: .
    runtime: nvidia
    volumes: 
     - "./output:/app/output"
    command: python3 yolo_opencv.py --quiet ${QUIET} --input ${STREAM} --invertcolor ${INVERT_COLOR} --fpsthrottle ${FPS_THROTTLE}
    restart: unless-stopped

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Africa/Johannesburg
      - PORT=1880
    network_mode: host
    volumes:
      - ./node-red-data:/data
      - ./output:/detected
    depends_on: 
      - rtsp-yolo-python
    restart: unless-stopped