version: "3.3"
services:
  rtsp-yolo-python-cam1:
    build: .
    runtime: nvidia
    volumes: 
     - "./output:/app/output"
    command: python3 yolo_opencv.py --quiet ${CAM1_QUIET} --input ${CAM1_STREAM} --invertcolor ${CAM1_INVERT_COLOR} --fpsthrottle ${CAM1_FPS_THROTTLE}
    restart: unless-stopped

  rtsp-yolo-python-cam2:
    build: .
    runtime: nvidia
    volumes: 
     - "./output:/app/output"
    command: python3 yolo_opencv.py --quiet ${CAM2_QUIET} --input ${CAM2_STREAM} --invertcolor ${CAM2_INVERT_COLOR} --fpsthrottle ${CAM2_FPS_THROTTLE}
    restart: unless-stopped

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Africa/Johannesburg
      - PORT=1880
    network_mode: host
    volumes:
      - ./node-red-data:/data
      - ./output:/detected
    restart: unless-stopped